# Autogenerated wrapper script for BQPD_jll for armv6l-linux-musleabihf-libgfortran3
export libbqpd_a, libbqpd_dense_a, qpsolve, qpsolve_dense

using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("BQPD")
JLLWrappers.@declare_file_product(libbqpd_a)
JLLWrappers.@declare_file_product(libbqpd_dense_a)
JLLWrappers.@declare_executable_product(qpsolve)
JLLWrappers.@declare_executable_product(qpsolve_dense)
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll)
    JLLWrappers.@init_file_product(
        libbqpd_a,
        "lib/libbqpd.a",
    )

    JLLWrappers.@init_file_product(
        libbqpd_dense_a,
        "lib/libbqpd_dense.a",
    )

    JLLWrappers.@init_executable_product(
        qpsolve,
        "bin/qpsolve",
    )

    JLLWrappers.@init_executable_product(
        qpsolve_dense,
        "bin/qpsolve_dense",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
